# Generated by Django 5.0.7 on 2024-07-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpstracker',
            old_name='lattitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='gpstracker',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
